// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGlxgAlJJmvTBI6PKDhexF9Q_Sae85o2U',
    appId: '1:154029402657:web:a7c0d1bfc2653df4e95160',
    messagingSenderId: '154029402657',
    projectId: 'stomata-blockchain',
    authDomain: 'stomata-blockchain.firebaseapp.com',
    storageBucket: 'stomata-blockchain.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDFfaeKtmaRMpsiyWGr6QJzrhGYBOW_gE',
    appId: '1:154029402657:android:fa70a79346f4536ae95160',
    messagingSenderId: '154029402657',
    projectId: 'stomata-blockchain',
    storageBucket: 'stomata-blockchain.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8LBW3gccBwbiMVEjXjBZowSMav0J18hY',
    appId: '1:154029402657:ios:18b25196be23581fe95160',
    messagingSenderId: '154029402657',
    projectId: 'stomata-blockchain',
    storageBucket: 'stomata-blockchain.firebasestorage.app',
    iosBundleId: 'com.example.stomataApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8LBW3gccBwbiMVEjXjBZowSMav0J18hY',
    appId: '1:154029402657:ios:18b25196be23581fe95160',
    messagingSenderId: '154029402657',
    projectId: 'stomata-blockchain',
    storageBucket: 'stomata-blockchain.firebasestorage.app',
    iosBundleId: 'com.example.stomataApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGlxgAlJJmvTBI6PKDhexF9Q_Sae85o2U',
    appId: '1:154029402657:web:296f106545f44728e95160',
    messagingSenderId: '154029402657',
    projectId: 'stomata-blockchain',
    authDomain: 'stomata-blockchain.firebaseapp.com',
    storageBucket: 'stomata-blockchain.firebasestorage.app',
  );
}
